steps:
  # Entrypoint, timeout and environment variables
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    timeout: 240s
    args: ['compute', 'instances', 
           'add-iam-policy-binding', 'instance-1',
           '--member=rambhargav0@gmail.com', 
           '--role=roles/compute.instanceAdmin.v1']
    env:
      - 'CLOUDSDK_COMPUTE_REGION=us-central1'
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
# [END cloudbuild_basic_config]
